/*
 * This source file was generated by the Gradle 'init' task
 */

package org.example;

import org.w3c.dom.*;
import javax.xml.parsers.*;
import java.io.File;

public class App {
    public static void main(String[] args) {
        try {
            File file = new File("src/main/resources/data.xml");
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
            Document doc = dBuilder.parse(file);
            doc.getDocumentElement().normalize();

            NodeList recordList = doc.getElementsByTagName("record");

            for (int i = 0; i < recordList.getLength(); i++) {
                Node node = recordList.item(i);
                if (node.getNodeType() == Node.ELEMENT_NODE) {
                    Element record = (Element) node;

                    String name = getTagValue("name", record);
                    String postalZip = getTagValue("postalZip", record);
                    String region = getTagValue("region", record);
                    String country = getTagValue("country", record);
                    String address = getTagValue("address", record);
                    String list = getTagValue("list", record);

                    System.out.println("Name: " + name);
                    System.out.println("Postal/Zip: " + postalZip);
                    System.out.println("Region: " + region);
                    System.out.println("Country: " + country);
                    System.out.println("Address: " + address);
                    System.out.println("List: " + list);
                    System.out.println("------------");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static String getTagValue(String tag, Element element) {
        NodeList nlList = element.getElementsByTagName(tag);
        if (nlList != null && nlList.getLength() > 0) {
            NodeList subList = nlList.item(0).getChildNodes();

            if (subList != null && subList.getLength() > 0) {
                return subList.item(0).getNodeValue();
            }
        }
        return "N/A";
    }
}
